// app-svelte/src/pages/_layout.svelte
<!-- routify:options preload="proximity" -->
<script>
    import { onMount } from "svelte"
    import Header from "../components/Header.svelte"
    import Footer from "../components/Footer.svelte"
    import { bgColor, headerClass } from "../stores"

    // Style body and Header
    onMount(() => { 
        bgColor.subscribe(color => {
            document.body.style.background = color
        })
    })
</script>

<section id="layout">
    <Header backgroundClass={$headerClass} />
    <slot />
    <Footer />
</section>

<style>
    #layout{
        height: 100vh;
        display: grid;
        grid-template-rows: auto 1fr auto;
    }
</style>

// app-vue/src/pages/_layout.vue
<script setup>
    import Header from "../components/Header.vue"
    import Footer from "../components/Footer.vue"
    import { bgColor, headerClass } from "../stores"
    bgColor.subscribe(color => { document.body.style.background = color })
</script>

<section id="layout">
    <Header backgroundClass={$headerClass} />
    <slot />
    <Footer />
</section>

<style scoped>
    #layout{
        height: 100vh;
        display: grid;
        grid-template-rows: auto 1fr auto;
    }
</style>
