// app-svelte/src/components/CodeBox.svelte
<script>
    import { bgColor, headerClass } from "../stores"
    
    let bodyCode, headerCode
    headerClass.subscribe(hClass => {
        headerCode = `<Header backgroundClass="${hClass}" />`
    })
    bgColor.subscribe(bCol => {
        bodyCode = `document.body.styles="${bCol}"`
    })
    
</script>

<div id="codebox">
    <code>{headerCode}</code>
    <code>{bodyCode}</code>
</div>

// app-react/src/components/CodeBox.jsx
//import { bgColor, headerClass } from "../stores"

export default function CodeBox() {

    let bodyCode, headerCode
    /*headerClass.subscribe(hClass => {
        headerCode = `<Header backgroundclassName="${hClass}" />`
    })
    bgColor.subscribe(bCol => {
        bodyCode = `document.body.styles="${bCol}"`
    })*/

    return (
        <div id="codebox">
            <code>{headerCode}</code>
            <code>{bodyCode}</code>
        </div>
    )
}
