// app-vue/src/components/Footer.vue
<template>
    <div id="footer" class="turretRoad">
        Project source code on <a href="https://github.com/andreaabellera/FreeTheEgg">Github</a>
    </div>
</template>

<style scoped>
    #footer{
        background-color: var(--black);
        color: var(--brightGreen);
        padding: 2vh 0 1vh 1vw;
        border-top: 3px solid var(--blue);
    }

    #footer a{
        color: var(--yellow) !important;
    }
</style>

// app-react/src/components/Footer.jsx
export default function Footer() {
    return (
        <div id="footer" className="turretRoad">
            Project source code on <a href="https://github.com/andreaabellera/FreeTheEgg">Github</a>
        </div>
    )
}

{/* <style>
    #footer{
        background-color: var(--black);
        color: var(--brightGreen);
        padding: 2vh 0 1vh 1vw;
        border-top: 3px solid var(--blue);
    }

    #footer a{
        color: var(--yellow) !important;
    }
</style> */}
